### ISSUE TITLE
Design Payment Invoice UI

### ISSUE THREAD

**Issue by Brackleycassinga** [ukama/ukama#303]
![Screen Shot 2022-08-04 at 16.26.50.png](https://images.zenhubusercontent.com/5ea2a2d34d7b4905596b6d0b/ccab4495-320e-41d1-867a-a0fbca87ef3a)

- [x]  Create a node Typescript project and implement pdfkit lib to stream invoices

- [x] Upload generated pdf to s3 then return url

**Comment by salman-codewar** [comment]
Its an old design, we've billing system and invoicing structure now. We can close this one.
