### ISSUE TITLE
Ory Oathkeeper helmchart deployment 

### ISSUE THREAD

**Issue by Brackleycassinga** [ukama/ukama#485]
We need to use Ory Oathkeeper as a reverse proxy that will sits in front of our APIs gateway and microservices, and provides authentication and authorization features. We will  integrate it with our existing Ory Kratos and Ory Keto to provide a complete identity and access management solution for our API gateway.

**Comment by salman-codewar** [comment]
This ticket is obsolete. We went with Kratos + Keto solution ([ref](#510 )). Closing this ticket.
